### ISSUE TITLE
项目详情选择供应商

### ISSUE THREAD

**Issue by limijiaoyin-sean** [limijiaoyin/Yuanyang-server#17]
选择了A，显示选中的是B，消息正常发送。

当项目已完成时，显示的中标单位是正确的：
![8d0e3523-a1ad-43da-89ea-ac3f34d7131d](https://cloud.githubusercontent.com/assets/9670529/8575098/cabdd60e-25cc-11e5-9685-b3626996789a.png)

**Comment by thrbowl** [comment]
Fixed
