### ISSUE TITLE
后台-供应商列表

### ISSUE THREAD

**Issue by limijiaoyin-sean** [limijiaoyin/Yuanyang-server#25]
1.经营单位筛选没做出来
2.供应商条目中经营范围为对齐
3.最上有评分的供应商打不开详情页面
![ecc44988-b620-46b8-870f-9e5f4f87c3ed](https://cloud.githubusercontent.com/assets/9670529/8668310/50d2a904-2a3c-11e5-873c-20ad477b3c7e.png)

**Comment by thrbowl** [comment]
Fixed
