### ISSUE TITLE
基本信息

### ISSUE THREAD

**Issue by limijiaoyin-sean** [limijiaoyin/Yuanyang-server#3]
- [x] 所有输入框未校验特殊字符				
- [x] 校验顺序不正确						
- [x] 联系电话校验时屏蔽了177号段				
- [x] 选公司地址-城市列表，返回直接退到注册页面	
- [x] 选择城市的搜索框不可用
- [x] 选城市时光标持续在闪
- [ ] 账号已注册时，注册提示“操作失败”			
- [x] 经营范围提示“最多选择一个一级，5个二级”

**Comment by jarvys** [comment]
@limijiaoyin-sean 特殊字符有哪些

**Comment by jarvys** [comment]
@limijiaoyin-sean 银行卡位数如何校验，不同的银行账号位数不同
